name: Selenium Ide CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-lates
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: null
      dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no--restore
    - name: Run tests
      run: dotnet tests --verbosity normal
